### PR TITLE
AWS SNS

### PR DESCRIPTION
**Pull request by Mochaka**
I added AWS SNS, however i needed to use the AWS SDK since there's not much documentation on sending raw payloads. Also wasn't able to create a mock request for phpspec.

### CODE REVIEW

**Comment by matthewbdaly** [comment]
I'm a bit dubious about including the AWS SDK by default. I'm inclined to use `suggest` instead of `require` for that.

Ideally we'd only use Guzzle for making HTTP requests, but that might be a lot of work otherwise. You could probably find out what the request is using a debugging proxy like Charles or Fiddler, and that would be the ideal solution, but I'll accept the pull request if you make the AWS SDK a suggested dependency.

**Comment by matthewbdaly** [comment]
Regarding the test, I would mock the SDK and have it return the response it would normally gove to that call. That would be the simplest way to test it.

**Comment by Mochaka** [comment]
Okay, i'll give that a go

**Comment by matthewbdaly** [comment]
I've merged this in, albeit with a few changes.

It was a bit of a pain testing it as is since it created the AWS SNS client in the constructor. What I've therefore done is made the second optional argument to the driver's constructor be the SNS client - that way you can pass through the SNS client directly. I've also made the AWS SDK a suggestion and a dev dependency only - if users want to use AWS SNS they'll need to explicitly add it to the project, and I've updated the README accordingly.

If at some point you can come back to it and refactor it to implement the request at a lower level using Guzzle, that would be fantastic (the whole AWS SDK is overkill for just sending SMS messages, so I would rather use Guzzle if at all possible), but no pressure - it still makes it easy to switch SMS provider at will so it meets the main goals of the project, and I'm happy with that for now.

**Comment by matthewbdaly** [comment]
I've tagged a new release that includes this functionality.

I don't have an AWS account set up so if you find any issues with it please open an issue to report it.

**Pull request merged**
